version: "3.3"

services:
  podinfo:
    image: stefanprodan/podinfo
    expose:
      - "9898"

  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    volumes:
      - "./htpasswd:/htpasswd:ro"
    command:
      - '--http-address=0.0.0.0:8080'
      - '--upstream=http://podinfo:9898'
      - '--cookie-secret=OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w='
      # dummy oauth setting
      - '--redirect-url=http://locahost:8081/oauth2/callback'
      - '--client-id=ddddd'
      - '--client-secret=dfdfdfdf'
      - '--email-domain=*'
      # make it working under http and without proper oauth
      - '--display-htpasswd-form'
      - '--htpasswd-file=/htpasswd'
      - '--cookie-secure=false'
      - '--skip-auth-preflight'

  nginx:
    image: nginx #:1.18.0-alpine
    ports:
    - "8081:80"
    volumes:
    - "./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro"
